<!-- mainmenu.inc -->
<ul class="vertical medium-horizontal dropdown menu" data-responsive-menu="accordion medium-dropdown">
  <li class="menu-text logohomelink">
    <a href="Default-espanol.aspx">
			<?xml version="1.0" encoding="utf-8"?>
			<svg version="1.1" id="stickylogo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
				 viewBox="0 0 36 45.5" style="enable-background:new 0 0 36 45.5;" xml:space="preserve">
			<style type="text/css">
        #stickylogo {width: 35px;}
        #stickylogo .st0{fill:#FFFFFF;}
				#stickylogo .st1{fill:#1E1A57;}
			</style>
			<title>Artboard 2</title>
			<g>
				<polygon class="st0" points="17.3,0 0,0 0,36.3 17.3,45.5 	"/>
				<polygon class="st0" points="36,0 18.7,0 18.7,23.5 36,14.2 	"/>
				<polygon class="st0" points="36,15.6 18.7,24.9 18.7,45.5 36,36.3 	"/>
				<g>
					<polygon class="st1" points="9.4,12.7 9.4,5.4 8.3,5.4 8.3,12.7 3.9,12.7 3.9,13.9 8.3,13.9 8.3,35.3 9.4,35.3 9.4,13.9
						13.8,13.9 13.8,12.7 		"/>
					<rect x="11.1" y="9.9" class="st1" width="1.2" height="1.3"/>
					<rect x="5.5" y="9.9" class="st1" width="1.2" height="1.3"/>
					<rect x="11.1" y="15.2" class="st1" width="1.2" height="1.3"/>
					<rect x="5.5" y="15.2" class="st1" width="1.2" height="1.3"/>
				</g>
				<path class="st1" d="M30.9,9.1c-0.1-1.5-0.7-2.9-1.7-4l-0.6-0.7l-0.4,0.8c-0.1,0.1-0.1,0.3-0.2,0.4c-0.4-0.5-0.7-1-0.9-1.5
					l-0.3-0.9l-0.6,0.7C26,4,23.8,6.6,23.8,9.7c0,1.7,1.2,3.2,2.9,3.5V15h1.2v-1.3l0,0v-0.5c0.7-0.1,1.4-0.5,1.9-1
					C30.6,11.3,31,10.2,30.9,9.1z M29,11.4c-0.3,0.3-0.7,0.5-1.1,0.6v-1.5c0-0.3-0.3-0.6-0.6-0.5c-0.3,0-0.5,0.2-0.5,0.5v0.8l0,0V12
					c-1.1-0.3-1.8-1.2-1.8-2.3c0-1.8,0.9-3.4,1.5-4.3c0.3,0.6,0.7,1.1,1.2,1.6l0.5,0.5l0.4-0.6c0.1-0.1,0.2-0.3,0.3-0.4
					c0.5,0.8,0.8,1.7,0.9,2.6C29.8,10,29.5,10.8,29,11.4z"/>
				<path class="st1" d="M30.2,28.1c-0.9,0-1.7,0.3-2.3,0.9v-0.3c0-1.3,1-2.3,2.3-2.3v-1.2c-1.2,0-2.2,0.6-2.9,1.6
					c-0.6-1-1.7-1.6-2.9-1.6v1.2c1.3,0,2.3,1,2.3,2.3V29c-1.4-1.3-3.6-1.2-4.9,0.3c-0.6,0.6-0.9,1.5-0.9,2.3h1.2c0-1.3,1-2.3,2.3-2.3
					c1.3,0,2.3,1,2.3,2.3v0.2c-1.1-0.7-2.6-0.3-3.2,0.8c-0.2,0.4-0.3,0.8-0.3,1.2h1.1c0-0.7,0.6-1.2,1.3-1.1c0.6,0,1.1,0.5,1.1,1.1v0.9
					h-0.9v1.2h2.9v-1.2h-0.9v-0.9c0-0.7,0.6-1.2,1.3-1.1c0.6,0,1.1,0.5,1.1,1.1h1.2c0-1.3-1.1-2.4-2.4-2.4c-0.4,0-0.8,0.1-1.2,0.3v-0.2
					c0-1.3,1-2.3,2.3-2.3c1.3,0,2.3,1,2.3,2.3h1.2C33.7,29.7,32.1,28.1,30.2,28.1z"/>
			</g>
			</svg>
    </a>
  </li>
  <li><a href="programs-espanol.aspx">Programas</a></li>
  <li><a href="admissions-espanol.aspx">Admisi&oacute;n</a></li>
  <!-- <li><a href="trabaja-mientras-estudias.aspx">Trabaja mientras Estudias</a></li> -->
  <li><a href="campus-life-espanol.aspx">Vida Estudiantil</a></li>
  <li><a href="about-espanol.aspx">Somos SJI</a></li>
  <li><a href="contact-us-espanol.aspx">Cont&aacute;ctenos</a></li>
</ul>
<!-- /mainmenu.inc -->
