<aside class="floatingcontainer">
	<a class="fixedrfi" href="https://marian.elluciancrmrecruit.com/Apply/Account/Create?f=991a68df-d47e-480a-8c93-f9c7543a543e&o=41234cec-6cc1-4a93-a8fe-5b7737391137&s=51232727-d65a-e911-80d6-0a1cd54f4e24&IsInquiry=True">Request your free brochure</a>
</aside>

<section class="formoutercontainer">
	<div class="row column text-center">
		<div class="row column">
			<p class="formheadertitle" style="font-weight: 700; font-size: 46px; line-height: 1.1; color: white; margin-bottom: 3rem;">Tell us more.</p>
		</div>
		<a style="background: transparent; border: 1px solid #dadb25; color: #dadb25;" href="https://marian.elluciancrmrecruit.com/Apply/Account/Create?f=991a68df-d47e-480a-8c93-f9c7543a543e&o=41234cec-6cc1-4a93-a8fe-5b7737391137&s=51232727-d65a-e911-80d6-0a1cd54f4e24&IsInquiry=True" class="button large">Learn more</a>
	</div>
</section>


<!--
DEPRECATED ON 2/2/2021. REPLACED BY ELLUCIAN FORM

<section class="formoutercontainer" id="formreveal">
	<div class="formcontainer small-12 large-8 large-offset-2 columns">
		<form action="" method="post" id="sjirfi">
			<div class="row column">
				<p class="formheadertitle" style="font-weight: 700; font-size: 46px; line-height: 1.1;">Tell us more.</p>
			</div>

			<div class="row">
				<div class="small-12 medium-6 columns"><input type="text" id="txtFname" placeholder="First name" aria-label="first name" ></div>
				<div class="small-12 medium-6 columns"><input type="text" id="txtLname" placeholder="Last name" aria-label="last name"></div>
			</div>

			<div class="row">
				<div class="small-12 columns"><input type="text" id="txtStreetAddress" placeholder="Street address" aria-label="address"></div>
			</div>

			<div class="row">
				<div class="small-12 medium-6 columns"><input type="text" id="txtCity" placeholder="City" aria-label="city"></div>
				<div class="small-12 medium-3 columns">
					<select name="dropdown" id="txtState" aria-label="state">
						<option value="">State</option>
						<option value="AL">Alabama</option>
						<option value="AK">Alaska</option>
						<option value="AZ">Arizona</option>
						<option value="AR">Arkansas</option>
						<option value="CA">California</option>
						<option value="CO">Colorado</option>
						<option value="CT">Connecticut</option>
						<option value="DE">Delaware</option>
						<option value="FL">Florida</option>
						<option value="GA">Georgia</option>
						<option value="HI">Hawaii</option>
						<option value="ID">Idaho</option>
						<option value="IL">Illinois</option>
						<option value="IN">Indiana</option>
						<option value="IA">Iowa</option>
						<option value="KS">Kansas</option>
						<option value="KY">Kentucky</option>
						<option value="LA">Louisiana</option>
						<option value="ME">Maine</option>
						<option value="MD">Maryland</option>
						<option value="MA">Massachusetts</option>
						<option value="MI">Michigan</option>
						<option value="MN">Minnesota</option>
						<option value="MS">Mississippi</option>
						<option value="MO">Missouri</option>
						<option value="MT">Montana</option>
						<option value="NE">Nebraska</option>
						<option value="NV">Nevada</option>
						<option value="NH">New Hampshire</option>
						<option value="NJ">New Jersey</option>
						<option value="NM">New Mexico</option>
						<option value="NY">New York</option>
						<option value="NC">North Carolina</option>
						<option value="ND">North Dakota</option>
						<option value="OH">Ohio</option>
						<option value="OK">Oklahoma</option>
						<option value="OR">Oregon</option>
						<option value="PA">Pennsylvania</option>
						<option value="RI">Rhode Island</option>
						<option value="SC">South Carolina</option>
						<option value="SD">South Dakota</option>
						<option value="TN">Tennessee</option>
						<option value="TX">Texas</option>
						<option value="UT">Utah</option>
						<option value="VR">Vermont</option>
						<option value="VA">Virginia</option>
						<option value="WA">Washington</option>
						<option value="WV">West Virginia</option>
						<option value="WI">Wisconsin</option>
						<option value="WY">Wyoming</option>
					</select>
				</div>
				<div class="small-12 medium-3 columns"><input type="text" id="txtZip" placeholder="Zip" aria-label="zip"></div>
			</div>

			<div class="row">
				<div class="small-12 medium-6 columns">
					<input type="text" id="txtEmail" placeholder="Email" aria-label="email">
				</div>
				<div class="small-12 medium-6 columns">
					<input type="text" id="txtPhone"  placeholder="Phone" aria-label="phone">
				</div>
			</div>
			<div class="row column">
				<input type="text" id="txtHighSchoolGradYear"  placeholder="High School Graduation Year" aria-label="grad year">
				<input type="text" id="txtHighSchool"  placeholder="High School Name" aria-label="high school name">

				<select name="dropdown" id="txtAreYouCurrently"  class="parentSelection" aria-label="currently">
					<option id="iAm" value="">I am...</option>
					<option id="attendingHS" value="attending_high_school">Attending High School</option>
					<option id="attendingCollege" value="attending_college">Attending College</option>
					<option id="aParent" value="is_parent">A Parent</option>
				</select>

<select name="dropdown" id="txtProgramInterest" class="childSelection" onchange="$('.programInterestSelection').val($(this).val());" aria-label="program interest">
	<option id="iAmInterestedIn" value="">I am interested in...</option>
	<option id="interestBusinessAdmin" value="Business Administration">Business Administration</option>
	<option id="interestLiberalArts" value="Liberal Arts">Liberal Arts</option>
	<option id="interestIT" value="Information Technology">Information Technology</option>
</select>

			</div>
			<input type="hidden" name="english" value="english" id="language" style="display: none;">
		</form>

		<div class="row column">
			<button type="button" id="ButtonSubmit" class="button secondary expanded" name="request info">REQUEST INFO</button>
		</div>

	</div>
</section>

<style media="screen">
	.enespanol #language {display: block;}
</style> -->
